server:
  port: 8080
spring:
  cloud:
    gateway:
#      default-filters:
#        - AddResponseHeader=source, samoyer
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
#logging:
#  level:
#    org:
#      springframework:
#        cloud:
#          gateway: trace
dubbo:
  application:
    name: dubbo-api-consumer
    qos-enable: true
    qos-port: 22224
    qos-accept-foreign-ip: false
  protocol:
    name: dubbo
    port: 22223
  registry:
    id: nacos-registry
    address: nacos://localhost:8848