// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileTwoTone from 'D:/JAVA/Projects/API Interface platform/samoyer-api-frontend/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SmileTwoTone';
export default { SmileTwoTone };
