// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/User","layout":false,"id":"1"},"2":{"path":"/User/login","parentId":"1","id":"2"},"3":{"path":"/User/register","parentId":"1","id":"3"},"4":{"path":"/interface_info/:id","name":"查看接口","icon":"smileTwoTone","hideInMenu":true,"parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/welcome","name":"🧡  欢迎使用","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/interface","name":"🔥  在线接口开放平台","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"/my","name":"🌈  我的接口","parentId":"ant-design-pro-layout","id":"7"},"8":{"path":"/admin","name":"😃  管理页","access":"canAdmin","parentId":"ant-design-pro-layout","id":"8"},"9":{"path":"/admin/InterfaceInfo","name":"⭐  接口管理","parentId":"8","id":"9"},"10":{"path":"/admin/interface_analysis","name":"⚡   接口分析","parentId":"8","id":"10"},"11":{"path":"/admin/User","name":"☀️  用户管理","parentId":"8","id":"11"},"12":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"12"},"13":{"path":"*","layout":false,"id":"13"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__User__Register__index" */'@/pages/User/Register/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__InterfaceInfo__index" */'@/pages/InterfaceInfo/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Interface__index" */'@/pages/Interface/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__My__index" */'@/pages/My/index.tsx')),
'8': React.lazy(() => import('./EmptyRoute')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Admin__InterfaceInfo__index" */'@/pages/Admin/InterfaceInfo/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Admin__InterfaceAnalysis__index" */'@/pages/Admin/InterfaceAnalysis/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Admin__User__index" */'@/pages/Admin/User/index.tsx')),
'12': React.lazy(() => import('./EmptyRoute')),
'13': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'D:/JAVA/Projects/API Interface platform/samoyer-api-frontend/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'D:/JAVA/Projects/API Interface platform/samoyer-api-frontend/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
